### ISSUE TITLE
callback function of onmessage that is not be triggered,when i restart script.

### ISSUE THREAD

**Issue by PandaTsui** [botorange/wechaty-puppet-padplus#47]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

```
npm install wechaty-puppet-padlus@next
```

2. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

- What is your wechaty version?
Answer:^0.28.3

- What is your wechaty-puppet-padplus version?
Answer: 0.0.126

- What is your node version? (run `node --version`)
Answer: 

- What os are you using
Answer: win10 and Ubuntu 16.04.4 LTS \n \l

## 2. Describe the bug

今天早晨发现，发送新消息后bot.on("message")的回调不会执行了，可以登录成功，login回调执行了。重新登录依然不行。

备注：bot.room.load(“xxxxx”).asy()可以正常调用，但是在群里说话回调onmessage的不会执行。
## 6. Full Output Logs

Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
 无
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```
</details>

[bug]

**Comment by su-chang** [comment]
Resolved already.
