### ISSUE TITLE
在获取好友信息的时候发现好友备注会变成好友最近操作修改群备注的一个群的群内备注

### ISSUE THREAD

**Issue by usersuccess** [botorange/wechaty-puppet-padplus#64]
1.wechaty 版本：0.28.3
wechaty-puppet-proplus 版本：0.0.129
node 版本： v10.16.3

![2019-10-31 14-35-58屏幕截图](https://user-images.githubusercontent.com/30675717/67924553-f6eb1a80-fbeb-11e9-8c8e-5c25d7a813eb.png)
此处我把群内备注修改后杀死进程重新登录,发现获取的好友信息中的备注变成群内名称(我和好友在同一个群),
再杀死进程重新登录又变回我给好友的备注

3.复现代码
 const contactList = await bot.Contact.findAll();
        console.log(contactList)
        let userInfo:any[] = [];
        for (let i = 0; i < contactList.length; i++) {
            const contact = contactList[i];
            if (contact.type() === Contact.Type.Personal) {
                const alias = await contact.alias();
                if (contact.friend()) {
                    log.info('Bot', `personal ${i}: ${contact.name()} (${alias}): ${contact.id}`);
                    if (alias != null) {
                        userInfo[i] = [contact.name(), alias, contact.id];
                        //db_insert(alias, contact.id, contact.name(), date);
                    }
                }
            }
        }
４：log

 Contact {
    domain: null,
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    id: 'wxid_swe61idufdbc22',
    payload:
     { alias: '无人莫',
       avatar:
        'http://wx.qlogo.cn/mmhead/ver_1/7NAPV7lAHqXTXOXC6P2Arb9HVAFllno4sRibtzPicIFEFopKmZMYlL4UIwkTIz9Qia2XGfIicnuhAEmBqiaShOUyCM6TQ8icz20WyvcI6ls0vsYCo/132',
       city: '',
       friend: true,
       gender: 0,
       id: 'wxid_swe61idufdbc22',
       name: '肖翔宁',
       province: '',
       signature: '',
       type: 1,
       weixin: 'wxid_swe61idufdbc22' },
    [Symbol(name)]: 'Contact',
    [Symbol(counter)]: 6 } ]

**Comment by su-chang** [comment]
Resolved already, please check it and close this issue.
