### ISSUE TITLE
In docker image node:10.15.0-alpine, throws file linux/fs.h not found

### ISSUE THREAD

**Issue by wencst** [botorange/wechaty-puppet-padplus#71]
## problem
When execute "npm i wechaty-puppet-padplus@latest" in alpine, it throws "……linux/fs.h: no such file or directory……" as below：
![图片](https://user-images.githubusercontent.com/3280860/68357832-94e16680-0151-11ea-883a-417a2f30e426.png)

## solution
https://github.com/huan/flash-store/issues/44

Need run `apk add linux-headers` before.

**Comment by su-chang** [comment]
Thank you for your issue and solution.
